### ISSUE TITLE
Update plugin for IntelliJ 2024.2

### ISSUE THREAD

**Issue by landsman** [sweet-mustard/test-nurturer#68]
![Screenshot 2024-08-13 at 18 01 49](https://github.com/user-attachments/assets/39b557d2-92cd-4a79-a691-0c75716cc028)

**Comment by wimdeblauwe** [comment]
Will need to update to Java 21 according to https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#platformVersions
